# Generated by Django 3.2.9 on 2021-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subject_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='book',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
