# Generated by Django 3.2.9 on 2022-01-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_level_subject_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='StudentsInTheClass', to='home.BaseUser'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubjectClass', to='home.level'),
        ),
        migrations.CreateModel(
            name='StudentParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='home.baseuser')),
                ('sudent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='home.baseuser')),
            ],
        ),
    ]
