# Generated by Django 3.2.9 on 2022-01-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220129_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.school'),
            preserve_default=False,
        ),
    ]
