# Generated by Django 3.2.9 on 2022-01-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_level_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparentrelation',
            name='sudent',
        ),
    ]
