# Generated by Django 3.2.9 on 2022-01-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_studentparentrelation_sudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentParentRelation',
        ),
    ]
