# Generated by Django 3.2.9 on 2022-01-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studentparentrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparentrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='home.baseuser'),
        ),
    ]
