# Generated by Django 3.2.9 on 2022-01-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_studentparentrelation_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparentrelation',
            name='parent',
        ),
    ]
