# Generated by Django 3.2.9 on 2022-01-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_studentparentrelation_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparentrelation',
            name='studentone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='home.baseuser'),
            preserve_default=False,
        ),
    ]
