# Generated by Django 3.2.9 on 2022-01-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_studentparentrelation_studentone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparentrelation',
            name='parent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='home.baseuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='studentone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='home.baseuser'),
        ),
    ]
