# Generated by Django 3.2.9 on 2022-02-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220129_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTASchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('meeting_agenda', models.TextField()),
                ('meeting_minutes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
