# Generated by Django 3.2.9 on 2022-02-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_ptaschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRemarkForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('remark', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_receiving_remark', to='home.baseuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_giving_remark', to='home.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRemarkForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.baseuser')),
            ],
        ),
    ]
