# Generated by Django 3.2.9 on 2022-02-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_adminremarkforstudent_teacherremarkforstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminremarkforstudent',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_giving_remark', to='home.baseuser'),
            preserve_default=False,
        ),
    ]
