# Generated by Django 4.0.2 on 2022-02-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_assignment_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='timetable')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.school')),
            ],
        ),
    ]
